prometheus:
  alertmanager:
    config:
      file_path:
      - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/alertmanager/config.yaml
      nfs_path: # TODO
      - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/alertmanager/NFS
  monitoring:
    config:
      file_path:
        - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/monitoring/config.yaml
      nfs_path: # TODO
        - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/monitoring/NFS
    rules:
      dir:
        - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/monitoring/rules
      sample_file:
        - /Users/varun.tomar/Documents/personal_github/mauto/data/sample-files/prometheus/rules/sample-rules.yaml
      sample_file_spark:
        - /Users/varun.tomar/Documents/personal_github/mauto/data/sample-files/prometheus/rules/sample-rules-spark.yaml
      nfs_path:  # TODO
        - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/elastalert/rules/NFS
    static_file:
      dir:
        - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/monitoring/static-files
      sample_file:
        - /Users/varun.tomar/Documents/personal_github/mauto/data/sample-files/prometheus/static-files/sample-staticfile.yaml
      nfs_path:  # TODO
        - //Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/monitoring/static-files/NFS
    repo:
      path:
        - /Users/varun.tomar/Documents/personal_github/mauto/data/temp-data/update_github_prometheus/prometheus
      url:
        - ssh://git@git.demo.com:7999/dp/prometheus.git
elastalert:
  rules:
    dir:
    - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/elastalert/rules
    nfs_path:  # TODO
    - //Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/elastalert/rules/NFS
    sample_file:
    - /Users/varun.tomar/Documents/personal_github/mauto/data/sample-files/elastalert/sample-elastalert-rules.yaml
  config:
    file_path:
      - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/elastalert/config.yaml 
    nfs_path: # TODO
      - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/elastalert
  repo_url:
    - ssh://git@git.demo.com:7999/dp/elastalert.git
  repo_path:
    - /tmp/update_git_elastalert/elastalert
  rules_repo_name:
    - 'rules'
  EA_rules_schema:
    - /Users/varun.tomar/Documents/personal_github/mauto/junk/demo-data/elastalert/EA-rules-schema.yaml
  temporary_ea_rules:
    - /Users/varun.tomar/Documents/personal_github/mauto/data/temp-data/temp_ea_rules
elasticsearch:
  hostname:
    aws: elasticsearch.default
  port: 9200
branch:
  - development
pagerduty_client_name:
  - elastalert
slack:
  channel:
    - test
index:
  nifi:
    - nifi-logs-*
  spark:
    - spark-logs-*
  service:
    - dw-access-logs-*
ssh_key_path:
  - /tmp/secret/id_rsa
env:
  - aws-stg
  - aws
log:
 filename:
   - /tmp/logs/automation.log
 level:
   - debug
kafka_docker_image: mesosphere/kafka-client
zookeeper_exclude_list:
  - zk.demo.com
  - zk01.demo.com
  - zk02.demo.com
  - zk03.demo.com