  ################# START JOB #########################
  - name: 'prj_name'
    email_configs:
    - send_resolved: true
      to:  # DO NOT REMOVE TAG: prj_name
      from: -prometheus@demo.com
      smarthost: outmail.demo.com:25
      headers:
        From: -prometheus@demo.com
        Subject: '{{ template "email.default.subject" . }} '
        To: '' # DO NOT REMOVE TAG: prj_name
      html: ' {{ template "email.default.html" . }} '
      require_tls: false
    
    
  ################### END JOB #########################  ################### END JOB #########################ALERT_RECEIVERS ABOVE  ################# START JOB #########################
  - name: 'prj_name'
    email_configs:
    - send_resolved: true
      to:  # DO NOT REMOVE TAG: prj_name
      from: -prometheus@demo.com
      smarthost: outmail.demo.com:25
      headers:
        From: -prometheus@demo.com
        Subject: '{{ template "email.default.subject" . }} '
        To: '' # DO NOT REMOVE TAG: prj_name
      html: ' {{ template "email.default.html" . }} '
      require_tls: false
    
    
  ################### END JOB #########################  ################### END JOB #########################  ################### END JOB #########################ALERT_RECEIVERS ABOVE